### ISSUE TITLE
Alice trusting the algorithm she just published 

### ISSUE THREAD

**Issue by aghatpande** [AlgoveraAI/generative-art#10]
Hi folks,
I am still running into an error at the "Alice trusts the published algorithm" step in the C2D workflow. Attached is the code and error I'm getting. My Data set is published on the Ocean marketplace (rinkeby) with the data token (Data_BPR), there are two datasets with the same data token. The algorithm is published with the token Alg_BPR and there are 3 of them. Wonder if this is the source of the problem? Any suggestions welcome.
mnkyNtigr

<img width="1440" alt="Screen Shot 2021-11-26 at 2 30 57 PM" src="https://user-images.githubusercontent.com/9574978/143623874-e5582bbf-e51b-4002-912d-b8efc29ab687.png">

**Comment by smejak** [comment]
I have also been getting some errors, but it eventually worked when I executed the cell a couple of times. I'm thinking that maybe you need to run the cells once in a specific order. So once you get the ALG did, run the next cell and if that produces an error, rerun the publishing as well. I'm not sure whether that will work.

**Comment by aghatpande** [comment]
Update from my side: the code works but getting identical error at last step as in Richard's notebook. See below

Exception: b'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.</p>\n'

**Comment by richardblythman** [comment]
@smejak I found out from Akshay from Ocean that this cell might fail if you try to run the following cell immediately after publish. This may be because the asset is not yet cached when the code tries to access it from Aquarius. I've added this info as a note in the notebook.

**Comment by richardblythman** [comment]
> Update from my side: the code works but getting identical error at last step as in Richard's notebook. See below
> 
> Exception: b'\n<title>404 Not Found</title>\n
> 
> # Not Found
> \n
> The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.
> 
> \n'

@aghatpande I think we can close this issue now right? The issue for retrieving results is still unresolved but contained within #6
