### ISSUE TITLE
Explore simpler alternatives to StyleGAN2

### ISSUE THREAD

**Issue by richardblythman** [AlgoveraAI/generative-art#2]
Now that we have decided to use the low-resolution CryptoPunks dataset, StyleGAN2 may be overkill. Also, the license is non-commercial.

Explore alternatives to StyleGAN2 based on the image resolution (and license). Create a list of 3-5 different options.

**Comment by aghatpande** [comment]
A search for "generative adversarial networks" leads to more than 4000 results  on GH! The link below (with more than 10k stars) documents multiple GANs implemented in PyTorch. 
https://github.com/eriklindernoren/PyTorch-GAN
Cheers, mnkyntigr

**Comment by smejak** [comment]
Perhaps DCGANs (https://arxiv.org/abs/1511.06434) might be a good alternative? In the repo that @aghatpande sent there's an example of them being used on MNIST and I also found this https://github.com/diegoalejogm/gans where they trained the model on CIFAR-10. They look reasonable for low-res images.

**Comment by Varkarakis** [comment]
for low-resolution, I have seen good result with BEGAN on CelebA(face db).  DCGAN, can be another alternative.

I found these medium articles : both use CryptoPunks and DCGAN 

1) https://medium.com/analytics-vidhya/deep-learning-w-cryptopunks-6b27dc767fab 

2) https://medium.com/mlearning-ai/generate-nft-cryptopunks-with-deep-convolutional-generative-adversarial-network-dcgan-db35f0a1adb4

also there is this link as well related to CryptoPunks: https://bastardganpunks.club/ 
their description says that they used StyleGAN2

**Comment by hollygrimm** [comment]
We could also fine-tune a pretrained model from StyleGAN2 or from this list of models from Justin Pinkney: https://github.com/justinpinkney/awesome-pretrained-stylegan2
