### ISSUE TITLE
Get C2D working for ocean.py example

### ISSUE THREAD

**Issue by richardblythman** [AlgoveraAI/generative-art#6]
The ocean.py docs give an example of code that runs an algorithm using Compute-2-Data (C2D).
Code: https://github.com/oceanprotocol/ocean.py/blob/main/READMEs/c2d-flow.md
Algorithm: https://github.com/trentmc/branin/blob/main/branin.py

This uses a standard Docker image provided by Ocean: oceanprotocol/algo_dockers

Create a notebook to showcase this example and confirm that it works. 

- [x] Everything up to and including run compute job
- [x] Retrieve results and plot

**Comment by aghatpande** [comment]
Going through the C2D quickstart flow. When I try this
#run barge: start ganache, Provider, Aquarius; deploy contracts; update ~/.ocean
./start_ocean.sh --with-provider2

(Sorry for the whiteouts, just my shell prompt). I tried the seed phrase on OP,s barge repo and also 'oceanprotocol' as passwords. Appreciate if you have any insights or help me diagnose, Cheers mnkyNtigr
<img width="988" alt="Screen Shot 2021-11-17 at 5 47 05 AM" src="https://user-images.githubusercontent.com/9574978/142189790-d301ba61-6438-47b6-bcd0-ffa5caff7bbc.png">
