### ISSUE TITLE
Write code to publish algorithm to Ocean marketplace

### ISSUE THREAD

**Issue by richardblythman** [AlgoveraAI/generative-art#8]
Write code (e.g. a notebook) to publish an algorithm on the marketplace. This algorithm can be published before the algorithm code has been finalised. We only need to give it a path to the location where the algorithm will be on GitHub and a suitable Docker image. 

See an example of a notebook for a different algorithm here https://github.com/AlgoveraAI/onshore/blob/main/notebooks/4-publish-model.ipynb

**Comment by aghatpande** [comment]
Going through the C2D quickstart flow. When I  try this
#run barge: start ganache, Provider, Aquarius; deploy contracts; update ~/.ocean
./start_ocean.sh  --with-provider2

(Sorry for the whiteouts, just my shell prompt). I tried the seed phrase on OP,s barge repo and also 'oceanprotocol' as passwords. Appreciate if you have any insights or help me diagnose, Cheers mnkyNtigr

<img width="988" alt="Screen Shot 2021-11-17 at 5 47 05 AM" src="https://user-images.githubusercontent.com/9574978/142188367-44f96652-f3d1-44db-accb-3a2cd7a170df.png">
